import { WeatherContextProvider } from "@/context";
import { Sidebar } from "@/components/sidebar";

import "@/styles/global.css";
import "./style.css";

export const metadata = {
  title: "Weather App",
  description: "Generated by firat altun",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ backgroundColor: " #100e1d" }}>
        <WeatherContextProvider>
          <div className="layout">
            <Sidebar />
            {children}
          </div>
        </WeatherContextProvider>
      </body>
    </html>
  );
}
